[package]
name = "media"
description = "FFmpeg decode, cpal output: renpy.audio.renpysound and video frames."
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
pyo3 = { workspace = true }
pyo3-ffi = { workspace = true }
cpal = { workspace = true }
ffmpeg-next = { workspace = true }
ffmpeg-sys-next = { workspace = true }
parking_lot = { workspace = true }
log = { workspace = true }
