#!/usr/bin/env python3
"""Build the SynthView game: a flat test pattern, a circle, a frame and a tile (stdlib PNG, no third-party art), the
game/*.rpy sources and view.plan.

    python3 harness/testgames/build.py view
"""
import pathlib
import shutil

from synthlib import gen

HERE = pathlib.Path(__file__).resolve().parent
W, H = 1277, 719
CASES = ["pattern", "bars", "frames", "circle", "sub"]

BARS = [(255, 255, 255), (255, 255, 0), (0, 255, 255), (0, 255, 0), (255, 0, 255), (255, 0, 0), (0, 0, 255)]


def pattern():
    c = gen.Canvas(W, H, (32, 32, 40))
    bw = W / 7.0
    for i, col in enumerate(BARS):   # bars in the middle band
        x0, x1 = int(round(i * bw)), int(round((i + 1) * bw))
        c.rect(x0, 200, x1 - x0, 90, col)
    c.rect(0, 0, W, 1, (255, 0, 0))
    c.rect(W - 1, 0, 1, H, (0, 255, 0))
    c.rect(0, H - 1, W, 1, (0, 0, 255))
    c.rect(0, 0, 1, H, (255, 255, 0))
    for (x, y, col) in ((1, 1, (255, 128, 0)), (W - 10, 1, (0, 128, 255)), (1, H - 10, (128, 255, 0)), (W - 10, H - 10, (255, 0, 128))):
        c.rect(x, y, 9, 9, col)   # 9 px markers just inside the frame
    cx, cy, r = W // 2, H // 2 + 120, 130
    for y in range(cy - r, cy + r + 1):
        for x in range(cx - r, cx + r + 1):
            d = (x - cx) ** 2 + (y - cy) ** 2
            if d <= r * r:
                c.rows[y][x * 4:x * 4 + 4] = bytes((240, 200, 60) if d > (r - 12) ** 2 else (60, 90, 200)) + b"\xff"
    c.rect(cx, cy - r, 1, 2 * r + 1, (255, 255, 255))   # 1 px cross through the circle centre
    c.rect(cx - r, cy, 2 * r + 1, 1, (255, 255, 255))
    return c


def circle():
    n = 301
    c = gen.Canvas(n, n, (0, 0, 0, 0))
    m = n // 2
    for y in range(n):
        for x in range(n):
            d = (x - m) ** 2 + (y - m) ** 2
            if d <= m * m:
                c.rows[y][x * 4:x * 4 + 4] = bytes((230, 80, 80) if d > (m - 10) ** 2 else (80, 200, 120)) + b"\xff"
    c.rect(m, 0, 1, n, (255, 255, 255))
    c.rect(0, m, n, 1, (255, 255, 255))
    return c


def frame():
    c = gen.Canvas(21, 21, (200, 200, 220))
    c.rect(0, 0, 21, 7, (220, 60, 60))
    c.rect(0, 14, 21, 7, (60, 60, 220))
    c.rect(0, 0, 7, 21, (60, 200, 60))
    c.rect(14, 0, 7, 21, (230, 200, 50))
    c.rect(7, 7, 7, 7, (30, 30, 50))
    return c


def tile():
    c = gen.Canvas(8, 8, (255, 255, 255))
    for y in range(8):
        for x in range(8):
            if (x + y) % 2:
                c.rect(x, y, 1, 1, (0, 0, 0))
    return c


def write_plan():
    lines = ["# Generated by build.py. The window keeps one size for the whole run (the gate checks it), so the cases vary what",
             "# is drawn. The padding comes from config.adjust_view_size (options.rpy).",
             "cmd auto on", "cmd click on", "wait menu True", "cmd click off", "settle 3", "shot 01-menu",
             "cmd start", "after_start", "cmd advance-to 8", "wait advance-done", "settle 2", "shot 02-say-8"]
    for i, c in enumerate(CASES):
        lines += ["cmd jump view_%s_case" % c, "settle 2", "shot %02d-%s" % (i + 3, c)]
    lines.append("quit")
    (HERE / "view.plan").write_text("\n".join(lines) + "\n")


def build(dest):
    write_plan()
    shutil.rmtree(dest / "game", ignore_errors=True)
    shutil.copytree(HERE / "game", dest / "game", ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "cache", "saves", "images"))
    img = dest / "game" / "images"
    pattern().png(img / "pattern.png", alpha=False)
    circle().png(img / "circle.png")
    frame().png(img / "frame.png", alpha=False)
    tile().png(img / "tile.png", alpha=False)


if __name__ == "__main__":
    import sys
    sys.path.insert(0, str(HERE.parent))
    build(HERE.parent / "build" / "view")
