#!/usr/bin/env python3
"""Probe game for the anisotropy investigation. Copies the textures of ../aniso (run its build.py first), writes
game/cases.rpy and probe.plan: for each geometry, texture and scaling, a shot with gl_anisotropic True and one with False,
both with the same geometry."""
import pathlib
import shutil

HERE = pathlib.Path(__file__).resolve().parent
SRC = HERE.parent / "aniso" / "game" / "textures"
TEX = HERE / "game" / "textures"
GEOMS = ("tilt", "mina", "minu")
TEXS = ("checker", "grating", "text")
SCALINGS = (("linear", "linear"), ("linear_mipmap_linear", "mip"))


def main():
    TEX.mkdir(parents=True, exist_ok=True)
    for t in TEXS:
        shutil.copy(SRC / (t + ".png"), TEX / (t + ".png"))
    out, plan = ["# Generated by build.py.\n"], ["settle 3"]
    for g in GEOMS:
        for t in TEXS:
            for s, short in SCALINGS:
                for on in (True, False):
                    n = "%s_%s_%s_%s" % (g, t, short, "on" if on else "off")
                    out.append("label case_%s:\n    call screen probe_case(%r, %r, %r, %r)\n" % (n, g, t, s, on))
                    plan += ["cmd jump case_" + n, "settle 2.5", "shot " + n]
    plan.append("quit")
    (HERE / "game" / "cases.rpy").write_text("\n".join(out))
    (HERE / "probe.plan").write_text("\n".join(plan) + "\n")
    print("wrote %d cases" % (len(plan) // 3))


if __name__ == "__main__":
    main()
