[package]
name = "pyhost"
description = "Embedded static CPython 3.12: build, blob importer, inittab."
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
pyo3-ffi = { workspace = true }
anyhow = { workspace = true }
