//! Generated from CPython 3.12 `_compat_pickle` (the `fix_imports=True` py2 to py3 name maps).
pub static IMPORT_MAPPING: &[(&str, &str)] = &[
    ("BaseHTTPServer", "http.server"),
    ("CGIHTTPServer", "http.server"),
    ("ConfigParser", "configparser"),
    ("Cookie", "http.cookies"),
    ("Dialog", "tkinter.dialog"),
    ("DocXMLRPCServer", "xmlrpc.server"),
    ("FileDialog", "tkinter.filedialog"),
    ("HTMLParser", "html.parser"),
    ("Queue", "queue"),
    ("ScrolledText", "tkinter.scrolledtext"),
    ("SimpleDialog", "tkinter.simpledialog"),
    ("SimpleHTTPServer", "http.server"),
    ("SimpleXMLRPCServer", "xmlrpc.server"),
    ("SocketServer", "socketserver"),
    ("StringIO", "io"),
    ("Tix", "tkinter.tix"),
    ("Tkconstants", "tkinter.constants"),
    ("Tkdnd", "tkinter.dnd"),
    ("Tkinter", "tkinter"),
    ("UserDict", "collections"),
    ("UserList", "collections"),
    ("UserString", "collections"),
    ("__builtin__", "builtins"),
    ("_abcoll", "collections.abc"),
    ("_elementtree", "xml.etree.ElementTree"),
    ("_winreg", "winreg"),
    ("anydbm", "dbm"),
    ("cPickle", "pickle"),
    ("cStringIO", "io"),
    ("commands", "subprocess"),
    ("cookielib", "http.cookiejar"),
    ("copy_reg", "copyreg"),
    ("dbhash", "dbm.bsd"),
    ("dbm", "dbm.ndbm"),
    ("dumbdbm", "dbm.dumb"),
    ("dummy_thread", "_dummy_thread"),
    ("gdbm", "dbm.gnu"),
    ("htmlentitydefs", "html.entities"),
    ("httplib", "http.client"),
    ("markupbase", "_markupbase"),
    ("repr", "reprlib"),
    ("robotparser", "urllib.robotparser"),
    ("test.test_support", "test.support"),
    ("thread", "_thread"),
    ("tkColorChooser", "tkinter.colorchooser"),
    ("tkCommonDialog", "tkinter.commondialog"),
    ("tkFileDialog", "tkinter.filedialog"),
    ("tkFont", "tkinter.font"),
    ("tkMessageBox", "tkinter.messagebox"),
    ("tkSimpleDialog", "tkinter.simpledialog"),
    ("ttk", "tkinter.ttk"),
    ("urllib2", "urllib.request"),
    ("urlparse", "urllib.parse"),
    ("whichdb", "dbm"),
    ("xmlrpclib", "xmlrpc.client"),
];

pub static NAME_MAPPING: &[((&str, &str), (&str, &str))] = &[
    (("UserDict", "IterableUserDict"), ("collections", "UserDict")),
    (("UserDict", "UserDict"), ("collections", "UserDict")),
    (("UserList", "UserList"), ("collections", "UserList")),
    (("UserString", "UserString"), ("collections", "UserString")),
    (("__builtin__", "basestring"), ("builtins", "str")),
    (("__builtin__", "intern"), ("sys", "intern")),
    (("__builtin__", "long"), ("builtins", "int")),
    (("__builtin__", "reduce"), ("functools", "reduce")),
    (("__builtin__", "unichr"), ("builtins", "chr")),
    (("__builtin__", "unicode"), ("builtins", "str")),
    (("__builtin__", "xrange"), ("builtins", "range")),
    (("_multiprocessing", "Connection"), ("multiprocessing.connection", "Connection")),
    (("_socket", "fromfd"), ("socket", "fromfd")),
    (("exceptions", "ArithmeticError"), ("builtins", "ArithmeticError")),
    (("exceptions", "AssertionError"), ("builtins", "AssertionError")),
    (("exceptions", "AttributeError"), ("builtins", "AttributeError")),
    (("exceptions", "BaseException"), ("builtins", "BaseException")),
    (("exceptions", "BufferError"), ("builtins", "BufferError")),
    (("exceptions", "BytesWarning"), ("builtins", "BytesWarning")),
    (("exceptions", "DeprecationWarning"), ("builtins", "DeprecationWarning")),
    (("exceptions", "EOFError"), ("builtins", "EOFError")),
    (("exceptions", "EnvironmentError"), ("builtins", "EnvironmentError")),
    (("exceptions", "Exception"), ("builtins", "Exception")),
    (("exceptions", "FloatingPointError"), ("builtins", "FloatingPointError")),
    (("exceptions", "FutureWarning"), ("builtins", "FutureWarning")),
    (("exceptions", "GeneratorExit"), ("builtins", "GeneratorExit")),
    (("exceptions", "IOError"), ("builtins", "IOError")),
    (("exceptions", "ImportError"), ("builtins", "ImportError")),
    (("exceptions", "ImportWarning"), ("builtins", "ImportWarning")),
    (("exceptions", "IndentationError"), ("builtins", "IndentationError")),
    (("exceptions", "IndexError"), ("builtins", "IndexError")),
    (("exceptions", "KeyError"), ("builtins", "KeyError")),
    (("exceptions", "KeyboardInterrupt"), ("builtins", "KeyboardInterrupt")),
    (("exceptions", "LookupError"), ("builtins", "LookupError")),
    (("exceptions", "MemoryError"), ("builtins", "MemoryError")),
    (("exceptions", "NameError"), ("builtins", "NameError")),
    (("exceptions", "NotImplementedError"), ("builtins", "NotImplementedError")),
    (("exceptions", "OSError"), ("builtins", "OSError")),
    (("exceptions", "OverflowError"), ("builtins", "OverflowError")),
    (("exceptions", "PendingDeprecationWarning"), ("builtins", "PendingDeprecationWarning")),
    (("exceptions", "ReferenceError"), ("builtins", "ReferenceError")),
    (("exceptions", "RuntimeError"), ("builtins", "RuntimeError")),
    (("exceptions", "RuntimeWarning"), ("builtins", "RuntimeWarning")),
    (("exceptions", "StandardError"), ("builtins", "Exception")),
    (("exceptions", "StopIteration"), ("builtins", "StopIteration")),
    (("exceptions", "SyntaxError"), ("builtins", "SyntaxError")),
    (("exceptions", "SyntaxWarning"), ("builtins", "SyntaxWarning")),
    (("exceptions", "SystemError"), ("builtins", "SystemError")),
    (("exceptions", "SystemExit"), ("builtins", "SystemExit")),
    (("exceptions", "TabError"), ("builtins", "TabError")),
    (("exceptions", "TypeError"), ("builtins", "TypeError")),
    (("exceptions", "UnboundLocalError"), ("builtins", "UnboundLocalError")),
    (("exceptions", "UnicodeDecodeError"), ("builtins", "UnicodeDecodeError")),
    (("exceptions", "UnicodeEncodeError"), ("builtins", "UnicodeEncodeError")),
    (("exceptions", "UnicodeError"), ("builtins", "UnicodeError")),
    (("exceptions", "UnicodeTranslateError"), ("builtins", "UnicodeTranslateError")),
    (("exceptions", "UnicodeWarning"), ("builtins", "UnicodeWarning")),
    (("exceptions", "UserWarning"), ("builtins", "UserWarning")),
    (("exceptions", "ValueError"), ("builtins", "ValueError")),
    (("exceptions", "Warning"), ("builtins", "Warning")),
    (("exceptions", "ZeroDivisionError"), ("builtins", "ZeroDivisionError")),
    (("itertools", "ifilter"), ("builtins", "filter")),
    (("itertools", "ifilterfalse"), ("itertools", "filterfalse")),
    (("itertools", "imap"), ("builtins", "map")),
    (("itertools", "izip"), ("builtins", "zip")),
    (("itertools", "izip_longest"), ("itertools", "zip_longest")),
    (("multiprocessing", "AuthenticationError"), ("multiprocessing.context", "AuthenticationError")),
    (("multiprocessing", "BufferTooShort"), ("multiprocessing.context", "BufferTooShort")),
    (("multiprocessing", "ProcessError"), ("multiprocessing.context", "ProcessError")),
    (("multiprocessing", "TimeoutError"), ("multiprocessing.context", "TimeoutError")),
    (("multiprocessing.forking", "Popen"), ("multiprocessing.popen_fork", "Popen")),
    (("multiprocessing.process", "Process"), ("multiprocessing.context", "Process")),
    (("socket", "_socketobject"), ("socket", "SocketType")),
    (("urllib", "ContentTooShortError"), ("urllib.error", "ContentTooShortError")),
    (("urllib", "getproxies"), ("urllib.request", "getproxies")),
    (("urllib", "pathname2url"), ("urllib.request", "pathname2url")),
    (("urllib", "quote"), ("urllib.parse", "quote")),
    (("urllib", "quote_plus"), ("urllib.parse", "quote_plus")),
    (("urllib", "unquote"), ("urllib.parse", "unquote")),
    (("urllib", "unquote_plus"), ("urllib.parse", "unquote_plus")),
    (("urllib", "url2pathname"), ("urllib.request", "url2pathname")),
    (("urllib", "urlcleanup"), ("urllib.request", "urlcleanup")),
    (("urllib", "urlencode"), ("urllib.parse", "urlencode")),
    (("urllib", "urlopen"), ("urllib.request", "urlopen")),
    (("urllib", "urlretrieve"), ("urllib.request", "urlretrieve")),
    (("urllib2", "HTTPError"), ("urllib.error", "HTTPError")),
    (("urllib2", "URLError"), ("urllib.error", "URLError")),
    (("whichdb", "whichdb"), ("dbm", "whichdb")),
];
