# Viewport and padding test game (corpus key SynthView). An odd screen size, and a view that is smaller than the window,
# so the window shows letterbox bars of odd width. Any off-by-one in the viewport, the bars or the scaling shows in the
# flat test pattern. All art is generated by ../build.py.
define config.name = "Synth View"
define config.save_directory = "synth-view"
define config.screen_width = 1277
define config.screen_height = 719
define config.window_title = "Synth View"
define config.has_autosave = False
define config.has_quicksave = False
define config.developer = False
define config.rollback_enabled = False
define config.gl_resize = True

init python:
    def view_size(w, h):
        """Make the view 3 px narrower and 1 px lower than the window: the rest is padding of odd width."""
        return (max(64, w - 3), max(64, h - 1))

    config.adjust_view_size = view_size
