#!/usr/bin/env python3
"""Median tables (markdown) from data/runs.jsonl. Usage: summarize.py > results.md"""
import collections, json, os, statistics as st
here = os.path.dirname(os.path.abspath(__file__))
rows = [json.loads(l) for l in open(f"{here}/data/runs.jsonl")]
groups = collections.OrderedDict()
for r in rows:
    groups.setdefault((r["mode"], r["label"], r["engine"], r.get("cold", False)), []).append(r)


import re


def log_took(r):
    """Engine log.txt phase timings, both formats ("took 0.12s" on 7.x/8.0-8.2, "took 59 ms" on 8.5)."""
    p = f"{here}/out/{r['label']}/{r['engine']}_{r['mode']}_r{r['rep']}/log.txt"
    d = {}
    if os.path.exists(p):
        for k, v, u in re.findall(r"^(.*?) took ([\d.]+) ?(ms|s)\b", open(p, errors="replace").read(), re.M):
            d[k.strip()] = float(v) / (1000.0 if u == "ms" else 1.0)
    return d


def med(vals):
    vals = [v for v in vals if v is not None]
    return st.median(vals) if vals else None


def f(v, n=1):
    return "-" if v is None else (f"{v:.{n}f}" if isinstance(v, float) else str(v))


def spread(vals, n=1):
    vals = [v for v in vals if v is not None]
    if len(vals) < 2:
        return ""
    return f" ({min(vals):.{n}f}-{max(vals):.{n}f})"


def ok(rs):
    return sum(1 for r in rs if r.get("done") and not r.get("traceback") and r.get("sweep_ok"))


print("# Measured results (median of reps; range in brackets)\n")
print("Generated by `summarize.py` from `data/runs.jsonl`. `ok` = runs that reached `done` with no traceback.txt and a clean sweep.\n")

print("## Video (measured window after 3 s warm-up)\n")
print("mv_fps = distinct movie frames handed to the renderer per second (`get_movie_texture` new=True); nominal 60. late = intervals > 1.5x nominal (25 ms); "
      "p99/max = interval between consecutive new frames (ms). draws/s = engine frames (`interface.frame_times`). CPU = process user+sys cores (os.times, whole process). "
      "GPU = ioreg `Device Utilization %` mean over the window and, in brackets, the idle baseline sampled for 3 s before launch (system-wide, includes WindowServer and anything else on the GPU; the baseline itself swung 0-70% during the campaign, so read GPU only as a coarse indicator). mv_call = mean ms inside `get_movie_texture` on the main thread.\n")
print("| label | engine | ok | mv_fps | dropped/window | late | p99 ms | max ms | draws/s | CPU cores | GPU % window (idle) | mv_call ms | RSS MB | peak footprint MB |")
print("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
for (mode, label, eng, cold), rs in groups.items():
    if mode != "video":
        continue
    W = [r["window"] for r in rs if "window" in r]
    if not W:
        print(f"| {label} | {eng} | {ok(rs)}/{len(rs)} | no window |")
        continue
    drop = [w["expected_frames"] - w["mv_frames"] for w in W]
    gpu = [r.get("gpu_dev_mean") for r in rs if "window" in r]
    print(f"| {label} | {eng} | {ok(rs)}/{len(rs)} | {f(med([w['mv_fps'] for w in W]))}{spread([w['mv_fps'] for w in W])} | {f(med(drop), 0)}{spread(drop, 0)} | "
          f"{f(med([w['mv_late'] for w in W]), 0)}{spread([w['mv_late'] for w in W], 0)} | {f(med([w['mv_p99'] for w in W]))} | {f(med([w['mv_max'] for w in W]))} | "
          f"{f(med([w['fps'] for w in W]))} | {f(med([w['cpu_cores'] for w in W]), 2)}{spread([w['cpu_cores'] for w in W], 2)} | "
          f"{f(med(gpu), 0)}{spread(gpu, 0)} ({f(med([r.get('gpu_idle_pct') for r in rs]), 0)}) | {f(med([w['mv_call_ms_mean'] for w in W]), 2)} | "
          f"{f(med([w['rss_b'] for w in W]), 0)} | {f(med([r['time'].get('peak_footprint_mb') for r in rs]), 0)} |")

print("\n## Startup (launch to interactive main menu; splash/consent screens auto-dismissed)\n")
print("since_launch = harness clock from just before exec (includes dyld, Python init, script load, init code, interface start). Phase columns are the engine's own `log.txt` timings (median). cold = `game/cache` deleted first (OS file cache stays warm).\n")
print("| engine | cache | ok | menu up s | Loading script | Running init code | Analyze screens | Prepare screens | Interface start | RSS at menu MB | wall (time -l) s |")
print("|---|---|---|---|---|---|---|---|---|---|---|")
for (mode, label, eng, cold), rs in groups.items():
    if mode != "startup":
        continue
    def took(k):
        v = []
        for r in rs:
            v.append(log_took(r).get(k))
        m = med(v)
        return f(m * 1000, 0) + " ms" if m is not None else "-"
    print(f"| {eng} | {'cold' if cold else 'warm'} | {ok(rs)}/{len(rs)} | {f(med([r.get('startup_s') for r in rs]), 2)}{spread([r.get('startup_s') for r in rs], 2)} | "
          f"{took('Loading script')} | {took('Running init code')} | {took('Analyze screens')} | {took('Prepare screens')} | {took('Interface start')} | "
          f"{f(med([r.get('startup_rss_mb') for r in rs]), 0)} | {f(med([r['time'].get('real_s') for r in rs]), 1)} |")

print("\n## Save / load (state after fast-reading the story for 45 s with auto-picked menu choices)\n")
print("screenshot+save = `renpy.take_screenshot()` then `renpy.save()` (3 saves per run, all pooled). load = `renpy.load()` call to first frame drawn after it (3 loads per run). "
      "rollback = rollback-log entries pickled into the save.\n")
print("| engine | ok | rollback entries | save file KB | screenshot ms | save ms | load to interact ms | load to first frame ms | RSS MB | textures MB |")
print("|---|---|---|---|---|---|---|---|---|---|")
for (mode, label, eng, cold), rs in groups.items():
    if mode != "saveload":
        continue
    ev = lambda r, k: [e for e in r.get("events", []) if e["ev"] == k]
    state = [e for r in rs for e in ev(r, "state")]
    saves = [e for r in rs for e in ev(r, "save")]
    loads = [e for r in rs for e in ev(r, "load")]
    print(f"| {eng} | {ok(rs)}/{len(rs)} | {f(med([e['rollback_entries'] for e in state]), 0)} | {f(med([e['bytes'] / 1024 for e in saves]), 0)} | "
          f"{f(med([e['screenshot_ms'] for e in saves]))} | {f(med([e['save_ms'] for e in saves]))}{spread([e['save_ms'] for e in saves])} | "
          f"{f(med([e['to_interact_ms'] for e in loads]))} | {f(med([e['to_first_frame_ms'] for e in loads]))}{spread([e['to_first_frame_ms'] for e in loads])} | "
          f"{f(med([e['rss_mb'] for e in state]), 0)} | {f(med([e['tex'][0] for e in state]), 0)} |")

print("\n## Large layered scenes: scene change with a 0.3 s dissolve (1 base + 3 layers, all full-resolution `Image`s)\n")
print("20 scenes, 2 passes over the same list, no prediction (worst case: first sight of the images, as after a load/jump). "
      "pass 0 = cold image cache; pass 1 = same scenes again. first frame = scene call to first drawn frame; hitch = max frame interval within 0.5 s of the call; "
      ">33 ms = frame intervals over 2 vsyncs. sync misses = `Cache.get` calls on the main thread that had to decode/upload (count per scene / ms per miss). "
      "Textures and cache at the end of the run.\n")
print("| engine | ok | pass | first frame ms (median / p95 over scenes) | hitch ms (median / p95) | frames >33 ms per scene | sync misses per scene | ms per sync miss | textures MB (count) | image cache MB | RSS MB | peak MB |")
print("|---|---|---|---|---|---|---|---|---|---|---|---|")
for (mode, label, eng, cold), rs in groups.items():
    if mode != "scenes":
        continue
    for p in (0, 1):
        fm, fp, hm, hp, o33, miss, msm, tex, tc, cmb, rss = [], [], [], [], [], [], [], [], [], [], []
        for r in rs:
            sc = [e for e in r.get("events", []) if e["ev"] == "scene" and e["pass"] == p]
            if not sc:
                continue
            ff = sorted(e["first_frame_ms"] for e in sc if e["first_frame_ms"] is not None)
            mm = sorted(e["max_ms"] for e in sc if e["max_ms"] is not None)
            fm.append(st.median(ff)); fp.append(ff[int(0.95 * (len(ff) - 1))])
            hm.append(st.median(mm)); hp.append(mm[int(0.95 * (len(mm) - 1))])
            o33.append(st.mean(e.get("over33", 0) for e in sc))
            miss.append(st.mean(e["c_miss"] + e["c_surf"] for e in sc))
            tm = sum(e["c_miss"] + e["c_surf"] for e in sc)
            msm.append(sum(e["c_sync_ms"] for e in sc) / tm if tm else None)
            tex.append(sc[-1]["tex"][0]); tc.append(sc[-1]["tex"][1]); cmb.append(sc[-1]["cache_mb"]); rss.append(sc[-1]["rss_mb"])
        pk = [next((e["peak_mb"] for e in r.get("events", []) if e["ev"] == "scenes_end"), None) for r in rs]
        if fm:
            print(f"| {eng} | {ok(rs)}/{len(rs)} | {p} | {f(med(fm), 0)} / {f(med(fp), 0)} | {f(med(hm), 0)} / {f(med(hp), 0)} | {f(med(o33), 1)} | {f(med(miss), 1)} | {f(med(msm), 1)} | "
                  f"{f(med(tex), 0)} ({f(med(tc), 0)}) | {f(med(cmb), 0)} | {f(med(rss), 0)} | {f(med(pk), 0)} |")

print("\n## Steady-state layered compositing (`stack`: base + 6 full-resolution layers panned by ATL for 12 s)\n")
print("| label | engine | ok | draws/s | p50 ms | p99 ms | max ms | frames >2x p50 | CPU cores | GPU % window (idle) | textures MB (count) | RSS MB |")
print("|---|---|---|---|---|---|---|---|---|---|---|---|")
for (mode, label, eng, cold), rs in groups.items():
    if mode != "stack":
        continue
    W = [r["window"] for r in rs if "window" in r]
    if not W:
        continue
    gpu = [r.get("gpu_dev_mean") for r in rs if "window" in r]
    print(f"| {label} | {eng} | {ok(rs)}/{len(rs)} | {f(med([w['fps'] for w in W]))} | {f(med([w['p50'] for w in W]))} | {f(med([w['p99'] for w in W]))} | {f(med([w['max'] for w in W]))} | "
          f"{f(med([w.get('late') for w in W]), 0)} | {f(med([w['cpu_cores'] for w in W]), 2)} | {f(med(gpu), 0)} ({f(med([r.get('gpu_idle_pct') for r in rs]), 0)}) | "
          f"{f(med([w['tex_b'][0] for w in W]), 0)} ({f(med([w['tex_b'][1] for w in W]), 0)}) | {f(med([w['rss_b'] for w in W]), 0)} |")
