# Synthetic narrative game (corpus key SynthStory). All art is generated by ../build.py.
define config.name = "Synth Story"
define config.save_directory = "synth-story"
define config.screen_width = 1280
define config.screen_height = 720
define config.window_title = "Synth Story"
define config.has_autosave = False
define config.has_quicksave = False
define config.developer = False
define config.rollback_enabled = False
