# Generated by build.py. One label per case; the harness jumps to it and takes one screenshot.

label case_tilt_checker_nearest:
    call screen aniso_case('tilt', 'checker', 'nearest', 'textures/cap_tilt_checker_nearest.png')

label case_tilt_checker_linear:
    call screen aniso_case('tilt', 'checker', 'linear', 'textures/cap_tilt_checker_linear.png')

label case_tilt_checker_mip:
    call screen aniso_case('tilt', 'checker', 'linear_mipmap_linear', 'textures/cap_tilt_checker_mip.png')

label case_tilt_grating_nearest:
    call screen aniso_case('tilt', 'grating', 'nearest', 'textures/cap_tilt_grating_nearest.png')

label case_tilt_grating_linear:
    call screen aniso_case('tilt', 'grating', 'linear', 'textures/cap_tilt_grating_linear.png')

label case_tilt_grating_mip:
    call screen aniso_case('tilt', 'grating', 'linear_mipmap_linear', 'textures/cap_tilt_grating_mip.png')

label case_tilt_text_nearest:
    call screen aniso_case('tilt', 'text', 'nearest', 'textures/cap_tilt_text_nearest.png')

label case_tilt_text_linear:
    call screen aniso_case('tilt', 'text', 'linear', 'textures/cap_tilt_text_linear.png')

label case_tilt_text_mip:
    call screen aniso_case('tilt', 'text', 'linear_mipmap_linear', 'textures/cap_tilt_text_mip.png')

label case_mina_checker_nearest:
    call screen aniso_case('mina', 'checker', 'nearest', 'textures/cap_mina_checker_nearest.png')

label case_mina_checker_linear:
    call screen aniso_case('mina', 'checker', 'linear', 'textures/cap_mina_checker_linear.png')

label case_mina_checker_mip:
    call screen aniso_case('mina', 'checker', 'linear_mipmap_linear', 'textures/cap_mina_checker_mip.png')

label case_mina_grating_nearest:
    call screen aniso_case('mina', 'grating', 'nearest', 'textures/cap_mina_grating_nearest.png')

label case_mina_grating_linear:
    call screen aniso_case('mina', 'grating', 'linear', 'textures/cap_mina_grating_linear.png')

label case_mina_grating_mip:
    call screen aniso_case('mina', 'grating', 'linear_mipmap_linear', 'textures/cap_mina_grating_mip.png')

label case_mina_text_nearest:
    call screen aniso_case('mina', 'text', 'nearest', 'textures/cap_mina_text_nearest.png')

label case_mina_text_linear:
    call screen aniso_case('mina', 'text', 'linear', 'textures/cap_mina_text_linear.png')

label case_mina_text_mip:
    call screen aniso_case('mina', 'text', 'linear_mipmap_linear', 'textures/cap_mina_text_mip.png')

label case_minu_checker_nearest:
    call screen aniso_case('minu', 'checker', 'nearest', 'textures/cap_minu_checker_nearest.png')

label case_minu_checker_linear:
    call screen aniso_case('minu', 'checker', 'linear', 'textures/cap_minu_checker_linear.png')

label case_minu_checker_mip:
    call screen aniso_case('minu', 'checker', 'linear_mipmap_linear', 'textures/cap_minu_checker_mip.png')

label case_minu_grating_nearest:
    call screen aniso_case('minu', 'grating', 'nearest', 'textures/cap_minu_grating_nearest.png')

label case_minu_grating_linear:
    call screen aniso_case('minu', 'grating', 'linear', 'textures/cap_minu_grating_linear.png')

label case_minu_grating_mip:
    call screen aniso_case('minu', 'grating', 'linear_mipmap_linear', 'textures/cap_minu_grating_mip.png')

label case_minu_text_nearest:
    call screen aniso_case('minu', 'text', 'nearest', 'textures/cap_minu_text_nearest.png')

label case_minu_text_linear:
    call screen aniso_case('minu', 'text', 'linear', 'textures/cap_minu_text_linear.png')

label case_minu_text_mip:
    call screen aniso_case('minu', 'text', 'linear_mipmap_linear', 'textures/cap_minu_text_mip.png')

define aniso_case_names = ['tilt_checker_nearest', 'tilt_checker_linear', 'tilt_checker_mip', 'tilt_grating_nearest', 'tilt_grating_linear', 'tilt_grating_mip', 'tilt_text_nearest', 'tilt_text_linear', 'tilt_text_mip', 'mina_checker_nearest', 'mina_checker_linear', 'mina_checker_mip', 'mina_grating_nearest', 'mina_grating_linear', 'mina_grating_mip', 'mina_text_nearest', 'mina_text_linear', 'mina_text_mip', 'minu_checker_nearest', 'minu_checker_linear', 'minu_checker_mip', 'minu_grating_nearest', 'minu_grating_linear', 'minu_grating_mip', 'minu_text_nearest', 'minu_text_linear', 'minu_text_mip']
